version: "3.5"
services:
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    expose:
      - "5432"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.4GB"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 25s
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  api1:
    build: .
    restart: always
    hostname: api1
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "1GB"

  api2:
    build: .
    restart: always
    hostname: api2
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "1GB"

  nginx:
    image: nginx
    hostname: api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "0.1GB"

  cache:
    hostname: cache
    image: redis:7-alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.5GB"
    command: ["redis-server", "--save", '""', "--appendonly", "no"]

volumes:
  postgres-db:

networks:
  default:
    driver: bridge
