version: "3.5"
services:
  api:
    build: .
    restart: always
    hostname: api
    depends_on:
      - db
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - selfhosted_ddosify
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  db:
    image: postgres
    # build:
    #   context: ./scripts/postgres
    #   dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - selfhosted_ddosify
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s

volumes:
  postgres-db:

networks:
  selfhosted_ddosify:
    external: true
