name: build image

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --tag leorcvargas/rinha-go:amd64 --platform linux/amd64 .
          docker buildx build --tag leorcvargas/rinha-go:arm64 --platform linux/arm64 .
          docker buildx build --tag leorcvargas/rinha-go:arm --platform linux/arm/v7 .
          docker buildx build --tag leorcvargas/rinha-go:darwin --platform darwin/amd64 .
          docker buildx build --tag leorcvargas/rinha-go:darwin-arm64 --platform darwin/arm64 .

      - name: push the image
        run: |
          docker push leorcvargas/rinha-go:amd64
          docker push leorcvargas/rinha-go:arm64
          docker push leorcvargas/rinha-go:arm
          docker push leorcvargas/rinha-go:darwin
          docker push leorcvargas/rinha-go:darwin-arm64

      - name: publish manifests
        run: |
          docker manifest create leorcvargas/rinha-go:latest \
            leorcvargas/rinha-go:amd64 \
            leorcvargas/rinha-go:arm64 \
            leorcvargas/rinha-go:arm \
            leorcvargas/rinha-go:darwin \
            leorcvargas/rinha-go:darwin-arm64
          docker manifest push leorcvargas/rinha-go:latest
